local tool = {}
      tool.waitFor=require("/_libs/WaitUtils")
      tool.processTrash=require("/ArkhamHorror/Scripts/TrashCan/TrashCan").process

local dropTimer = 0.8

local GlobalEvents = {}
--------------------------------------------------------------------------------
--- onObjectEnter : CONTAINER --------------------------------------------------
function onObjectEnterContainer(bag, obj)
    if string.find(string.lower(obj.getDescription()), string.lower(bag.getGMNotes()), 1, true) then
        --tool.waitFor.DropIntoBox(bag, obj, shuffleContainer, dropTimer)
    elseif string.find(string.lower(bag.getGMNotes()), 'trashcan', 1, true) then
        tool.waitFor.DropIntoBox(bag, obj, TrashFunction, dropTimer)
    end
end
--------------------------------------------------------------------------------
--- SHUFFLE FUNCTION -----------------------------------------------------------
function shuffleContainer(bag)
    printToAll('Shuffling : '..bag.getName()..' Bag', 'Yellow')
    bag.shuffle()
end
--------------------------------------------------------------------------------
--- TRASH FUNCTION -------------------------------------------------------------
function TrashFunction(TrashBag)
    tool.processTrash(TrashBag)
end

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
return GlobalEvents
