local debug = require("/_libs/debug/debug")
local onModLoad=require("/_libs/onModLoad/onModLoad")

function onLoad()
    debug.setDebugHotKeys()

    setGlobalVariables()
    onModLoad.MegaFreeze() -- You can also add GUIDs via {'guid1', 'guid2'....}
    onModLoad.FixHandZones(10)

    local GlobalEvents=require("/ArkhamHorror/GlobalEvents")
end

function setGlobalVariables()
    GlobalVariables=require("/ArkhamHorror/GlobalVariables")
end

function onUpdate()end